# Generated by Django 5.0.1 on 2024-01-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuesto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
