# Generated by Django 5.0.1 on 2024-01-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_impuesto_fecha_vencimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Impuesto',
            new_name='Vencimiento',
        ),
    ]
