# Generated by Django 5.0.1 on 2024-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rename_impuesto_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vencimiento',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vencimiento',
            name='impuesto',
            field=models.CharField(choices=[('Autónomo', 'Autónomo'), ('Cargas Sociales', 'Cargas Sociales')], max_length=30),
        ),
    ]
