# Generated by Django 5.0.1 on 2024-01-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=128)),
                ('CUIT', models.CharField(max_length=11)),
                ('domicilio', models.CharField(max_length=128)),
                ('localidad', models.CharField(choices=[('adrogue', 'Adrogué'), ('burzaco', 'Burzaco')], max_length=64)),
                ('provincia', models.CharField(choices=[('buenosaires', 'Buenos Aires'), ('mendoza', 'Mendoza')], max_length=64)),
                ('contacto_nombre', models.CharField(max_length=128)),
                ('celular', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('forma', models.CharField(choices=[('cooperativa', 'Cooperativa'), ('sociedad', 'Sociedad'), ('unipersonal', 'Unipersonal')], max_length=64)),
                ('situacion_iva', models.CharField(choices=[('monotributo', 'Monotributo'), ('Inscripto', 'Inscripto'), ('Exento', 'Exento')], max_length=64)),
                ('ingresos_brutos', models.CharField(choices=[('monotributo', 'Monotributo'), ('Inscripto', 'Inscripto'), ('Exento', 'Exento')], max_length=64)),
            ],
        ),
    ]
