# Generated by Django 5.0.1 on 2024-01-21 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estudiocastillo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CUIT',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='El CUITdebe tener 11 dígitos.'), django.core.validators.MaxLengthValidator(limit_value=11, message='El CUITdebe tener 11 dígitos.'), django.core.validators.RegexValidator(message='El CUITdebe tener 11 dígitos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='El número de celular debe tener 10 dígitos.'), django.core.validators.MinLengthValidator(limit_value=10, message='El número de celular debe tener 10 dígitos.'), django.core.validators.RegexValidator(message='El número de celular debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='forma',
            field=models.CharField(choices=[('Cooperativa', 'Cooperativa'), ('Sociedad', 'Sociedad'), ('Unipersonal', 'Unipersonal')], max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ingresos_brutos',
            field=models.CharField(choices=[('Convenio', 'Convenio'), ('Local', 'Local'), ('Unificado', 'Unificado')], max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(choices=[('Adrogue', 'Adrogué'), ('Burzaco', 'Burzaco'), ('Longchamps', 'Longchamps')], max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán')], max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='situacion_iva',
            field=models.CharField(choices=[('Monotributo', 'Monotributo'), ('Inscripto', 'Inscripto'), ('Exento', 'Exento')], max_length=64),
        ),
    ]
