# Generated by Django 5.0.1 on 2024-01-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estudiocastillo', '0002_alter_cliente_cuit_alter_cliente_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='honorarios',
            field=models.IntegerField(default=0),
        ),
    ]
