# Generated by Django 5.0.1 on 2024-01-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estudiocastillo', '0003_cliente_honorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='recibe_factura',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='honorarios',
            field=models.FloatField(default=0),
        ),
    ]
