# Generated by Django 5.0.1 on 2024-01-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estudiocastillo', '0004_cliente_recibe_factura_alter_cliente_honorarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='recibe_factura',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
    ]
